#!/bin/bash

# Install dependencies
echo "******************* installing SMA requirements needed for SMA to work. *******************"
pip3 install -q -r /sma/setup/requirements.txt

# Set permissions
chmod -R 775 /sma
chown -R 1000:1000 /sma
